//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrySWII_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Citas = new HashSet<Citas>();
            this.UsuMedico = new HashSet<UsuMedico>();
        }
    
        public string IdEmpleado { get; set; }
        public string ApeEmpPat { get; set; }
        public string ApeEmpMat { get; set; }
        public string NomEmpleado { get; set; }
        public string Sexo { get; set; }
        public string NroDNI { get; set; }
        public string Direccion { get; set; }
        public string IdDistrito { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public string IdEspecialidad { get; set; }
    
        public virtual ICollection<Citas> Citas { get; set; }
        public virtual Distrito Distrito { get; set; }
        public virtual Especialidades Especialidades { get; set; }
        public virtual ICollection<UsuMedico> UsuMedico { get; set; }
    }
}
