//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrySWII_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examenes
    {
        public Examenes()
        {
            this.Detalle_Examenes = new HashSet<Detalle_Examenes>();
        }
    
        public string IdExamen { get; set; }
        public string Examem { get; set; }
        public string IdPaciente { get; set; }
    
        public virtual ICollection<Detalle_Examenes> Detalle_Examenes { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
