//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrySWII_ADO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MiseladaEntities : DbContext
    {
        public MiseladaEntities()
            : base("name=MiseladaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Alergias> Alergias { get; set; }
        public DbSet<Citas> Citas { get; set; }
        public DbSet<Detalle_Examenes> Detalle_Examenes { get; set; }
        public DbSet<Detalle_Receta> Detalle_Receta { get; set; }
        public DbSet<Distrito> Distrito { get; set; }
        public DbSet<Empleado> Empleado { get; set; }
        public DbSet<Especialidades> Especialidades { get; set; }
        public DbSet<Examenes> Examenes { get; set; }
        public DbSet<Medicamento> Medicamento { get; set; }
        public DbSet<Paciente> Paciente { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
        public DbSet<UsuMedico> UsuMedico { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int usp_actualizarCita(string ccod, string emp, Nullable<System.DateTime> fecha, Nullable<System.TimeSpan> hinic, Nullable<System.TimeSpan> hfin, string estado)
        {
            var ccodParameter = ccod != null ?
                new ObjectParameter("ccod", ccod) :
                new ObjectParameter("ccod", typeof(string));
    
            var empParameter = emp != null ?
                new ObjectParameter("emp", emp) :
                new ObjectParameter("emp", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var hinicParameter = hinic.HasValue ?
                new ObjectParameter("hinic", hinic) :
                new ObjectParameter("hinic", typeof(System.TimeSpan));
    
            var hfinParameter = hfin.HasValue ?
                new ObjectParameter("hfin", hfin) :
                new ObjectParameter("hfin", typeof(System.TimeSpan));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizarCita", ccodParameter, empParameter, fechaParameter, hinicParameter, hfinParameter, estadoParameter);
        }
    
        public virtual int usp_actualizarEmpleado(string ecod, string empPat, string empMat, string nomEmp, string sexo, string dni, string dir, string dis, string tel, string cel, string email, string especialidad)
        {
            var ecodParameter = ecod != null ?
                new ObjectParameter("ecod", ecod) :
                new ObjectParameter("ecod", typeof(string));
    
            var empPatParameter = empPat != null ?
                new ObjectParameter("empPat", empPat) :
                new ObjectParameter("empPat", typeof(string));
    
            var empMatParameter = empMat != null ?
                new ObjectParameter("empMat", empMat) :
                new ObjectParameter("empMat", typeof(string));
    
            var nomEmpParameter = nomEmp != null ?
                new ObjectParameter("nomEmp", nomEmp) :
                new ObjectParameter("nomEmp", typeof(string));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("sexo", sexo) :
                new ObjectParameter("sexo", typeof(string));
    
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var dirParameter = dir != null ?
                new ObjectParameter("dir", dir) :
                new ObjectParameter("dir", typeof(string));
    
            var disParameter = dis != null ?
                new ObjectParameter("dis", dis) :
                new ObjectParameter("dis", typeof(string));
    
            var telParameter = tel != null ?
                new ObjectParameter("tel", tel) :
                new ObjectParameter("tel", typeof(string));
    
            var celParameter = cel != null ?
                new ObjectParameter("cel", cel) :
                new ObjectParameter("cel", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var especialidadParameter = especialidad != null ?
                new ObjectParameter("especialidad", especialidad) :
                new ObjectParameter("especialidad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizarEmpleado", ecodParameter, empPatParameter, empMatParameter, nomEmpParameter, sexoParameter, dniParameter, dirParameter, disParameter, telParameter, celParameter, emailParameter, especialidadParameter);
        }
    
        public virtual int usp_actualizarMedicamneto(string mcod, string nomMed, string tipo, string des, Nullable<decimal> pre, Nullable<int> stock)
        {
            var mcodParameter = mcod != null ?
                new ObjectParameter("mcod", mcod) :
                new ObjectParameter("mcod", typeof(string));
    
            var nomMedParameter = nomMed != null ?
                new ObjectParameter("nomMed", nomMed) :
                new ObjectParameter("nomMed", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var desParameter = des != null ?
                new ObjectParameter("des", des) :
                new ObjectParameter("des", typeof(string));
    
            var preParameter = pre.HasValue ?
                new ObjectParameter("pre", pre) :
                new ObjectParameter("pre", typeof(decimal));
    
            var stockParameter = stock.HasValue ?
                new ObjectParameter("stock", stock) :
                new ObjectParameter("stock", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizarMedicamneto", mcodParameter, nomMedParameter, tipoParameter, desParameter, preParameter, stockParameter);
        }
    
        public virtual int usp_actualizarPaciente(string pcod, string pacPat, string pacMat, string nomPac, string sexo, string dni, string dir, string dis, string tel, string cel, string email, string tipSag, string tal, string peso)
        {
            var pcodParameter = pcod != null ?
                new ObjectParameter("pcod", pcod) :
                new ObjectParameter("pcod", typeof(string));
    
            var pacPatParameter = pacPat != null ?
                new ObjectParameter("pacPat", pacPat) :
                new ObjectParameter("pacPat", typeof(string));
    
            var pacMatParameter = pacMat != null ?
                new ObjectParameter("pacMat", pacMat) :
                new ObjectParameter("pacMat", typeof(string));
    
            var nomPacParameter = nomPac != null ?
                new ObjectParameter("nomPac", nomPac) :
                new ObjectParameter("nomPac", typeof(string));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("sexo", sexo) :
                new ObjectParameter("sexo", typeof(string));
    
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var dirParameter = dir != null ?
                new ObjectParameter("dir", dir) :
                new ObjectParameter("dir", typeof(string));
    
            var disParameter = dis != null ?
                new ObjectParameter("dis", dis) :
                new ObjectParameter("dis", typeof(string));
    
            var telParameter = tel != null ?
                new ObjectParameter("tel", tel) :
                new ObjectParameter("tel", typeof(string));
    
            var celParameter = cel != null ?
                new ObjectParameter("cel", cel) :
                new ObjectParameter("cel", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var tipSagParameter = tipSag != null ?
                new ObjectParameter("TipSag", tipSag) :
                new ObjectParameter("TipSag", typeof(string));
    
            var talParameter = tal != null ?
                new ObjectParameter("Tal", tal) :
                new ObjectParameter("Tal", typeof(string));
    
            var pesoParameter = peso != null ?
                new ObjectParameter("Peso", peso) :
                new ObjectParameter("Peso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizarPaciente", pcodParameter, pacPatParameter, pacMatParameter, nomPacParameter, sexoParameter, dniParameter, dirParameter, disParameter, telParameter, celParameter, emailParameter, tipSagParameter, talParameter, pesoParameter);
        }
    
        public virtual int usp_cambiar_password(string user, string password)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_cambiar_password", userParameter, passwordParameter);
        }
    
        public virtual int usp_check_respuesta(string user, string respuesta)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var respuestaParameter = respuesta != null ?
                new ObjectParameter("respuesta", respuesta) :
                new ObjectParameter("respuesta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_check_respuesta", userParameter, respuestaParameter);
        }
    
        public virtual ObjectResult<usp_consultarCita_Result> usp_consultarCita(string ccod)
        {
            var ccodParameter = ccod != null ?
                new ObjectParameter("ccod", ccod) :
                new ObjectParameter("ccod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_consultarCita_Result>("usp_consultarCita", ccodParameter);
        }
    
        public virtual ObjectResult<usp_consultarCitasEmpleado_Result1> usp_consultarCitasEmpleado(string estado, Nullable<System.DateTime> fechaini, Nullable<System.DateTime> fechafin)
        {
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var fechainiParameter = fechaini.HasValue ?
                new ObjectParameter("fechaini", fechaini) :
                new ObjectParameter("fechaini", typeof(System.DateTime));
    
            var fechafinParameter = fechafin.HasValue ?
                new ObjectParameter("fechafin", fechafin) :
                new ObjectParameter("fechafin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_consultarCitasEmpleado_Result1>("usp_consultarCitasEmpleado", estadoParameter, fechainiParameter, fechafinParameter);
        }
    
        public virtual ObjectResult<usp_consultarEmpleado_Result> usp_consultarEmpleado(string ecod)
        {
            var ecodParameter = ecod != null ?
                new ObjectParameter("ecod", ecod) :
                new ObjectParameter("ecod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_consultarEmpleado_Result>("usp_consultarEmpleado", ecodParameter);
        }
    
        public virtual ObjectResult<usp_consultarPaciente_Result> usp_consultarPaciente(string pcod)
        {
            var pcodParameter = pcod != null ?
                new ObjectParameter("pcod", pcod) :
                new ObjectParameter("pcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_consultarPaciente_Result>("usp_consultarPaciente", pcodParameter);
        }
    
        public virtual ObjectResult<usp_consultarStockMedicamento_Result> usp_consultarStockMedicamento(string tipo)
        {
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_consultarStockMedicamento_Result>("usp_consultarStockMedicamento", tipoParameter);
        }
    
        public virtual ObjectResult<usp_consultarUsuario_Result> usp_consultarUsuario(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_consultarUsuario_Result>("usp_consultarUsuario", idParameter);
        }
    
        public virtual int usp_eliminarCita(string ccod)
        {
            var ccodParameter = ccod != null ?
                new ObjectParameter("ccod", ccod) :
                new ObjectParameter("ccod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_eliminarCita", ccodParameter);
        }
    
        public virtual int usp_eliminarEmpleado(string ecod)
        {
            var ecodParameter = ecod != null ?
                new ObjectParameter("ecod", ecod) :
                new ObjectParameter("ecod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_eliminarEmpleado", ecodParameter);
        }
    
        public virtual int usp_eliminarMedicamento(string mcod)
        {
            var mcodParameter = mcod != null ?
                new ObjectParameter("mcod", mcod) :
                new ObjectParameter("mcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_eliminarMedicamento", mcodParameter);
        }
    
        public virtual int usp_eliminarPaciente(string pcod)
        {
            var pcodParameter = pcod != null ?
                new ObjectParameter("pcod", pcod) :
                new ObjectParameter("pcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_eliminarPaciente", pcodParameter);
        }
    
        public virtual int usp_insertarCita(string emp, string pac, Nullable<System.DateTime> fecha, Nullable<System.TimeSpan> hinic, Nullable<System.TimeSpan> hfin, string estado)
        {
            var empParameter = emp != null ?
                new ObjectParameter("emp", emp) :
                new ObjectParameter("emp", typeof(string));
    
            var pacParameter = pac != null ?
                new ObjectParameter("pac", pac) :
                new ObjectParameter("pac", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var hinicParameter = hinic.HasValue ?
                new ObjectParameter("hinic", hinic) :
                new ObjectParameter("hinic", typeof(System.TimeSpan));
    
            var hfinParameter = hfin.HasValue ?
                new ObjectParameter("hfin", hfin) :
                new ObjectParameter("hfin", typeof(System.TimeSpan));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_insertarCita", empParameter, pacParameter, fechaParameter, hinicParameter, hfinParameter, estadoParameter);
        }
    
        public virtual int usp_insertarEmpleado(string empPat, string empMat, string nomEmp, string sexo, string dni, string dir, string dis, string tel, string cel, string email, string idEsp)
        {
            var empPatParameter = empPat != null ?
                new ObjectParameter("empPat", empPat) :
                new ObjectParameter("empPat", typeof(string));
    
            var empMatParameter = empMat != null ?
                new ObjectParameter("empMat", empMat) :
                new ObjectParameter("empMat", typeof(string));
    
            var nomEmpParameter = nomEmp != null ?
                new ObjectParameter("nomEmp", nomEmp) :
                new ObjectParameter("nomEmp", typeof(string));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("sexo", sexo) :
                new ObjectParameter("sexo", typeof(string));
    
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var dirParameter = dir != null ?
                new ObjectParameter("dir", dir) :
                new ObjectParameter("dir", typeof(string));
    
            var disParameter = dis != null ?
                new ObjectParameter("dis", dis) :
                new ObjectParameter("dis", typeof(string));
    
            var telParameter = tel != null ?
                new ObjectParameter("tel", tel) :
                new ObjectParameter("tel", typeof(string));
    
            var celParameter = cel != null ?
                new ObjectParameter("cel", cel) :
                new ObjectParameter("cel", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var idEspParameter = idEsp != null ?
                new ObjectParameter("idEsp", idEsp) :
                new ObjectParameter("idEsp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_insertarEmpleado", empPatParameter, empMatParameter, nomEmpParameter, sexoParameter, dniParameter, dirParameter, disParameter, telParameter, celParameter, emailParameter, idEspParameter);
        }
    
        public virtual int usp_insertarMedicamneto(string nomMed, string tipo, string des, Nullable<decimal> pre, Nullable<int> stock)
        {
            var nomMedParameter = nomMed != null ?
                new ObjectParameter("nomMed", nomMed) :
                new ObjectParameter("nomMed", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var desParameter = des != null ?
                new ObjectParameter("des", des) :
                new ObjectParameter("des", typeof(string));
    
            var preParameter = pre.HasValue ?
                new ObjectParameter("pre", pre) :
                new ObjectParameter("pre", typeof(decimal));
    
            var stockParameter = stock.HasValue ?
                new ObjectParameter("stock", stock) :
                new ObjectParameter("stock", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_insertarMedicamneto", nomMedParameter, tipoParameter, desParameter, preParameter, stockParameter);
        }
    
        public virtual int usp_insertarPaciente(string pacPat, string pacMat, string nomPac, string sexo, string dni, string dir, string dis, string tel, string cel, string email, string tipSag, string tal, string peso)
        {
            var pacPatParameter = pacPat != null ?
                new ObjectParameter("pacPat", pacPat) :
                new ObjectParameter("pacPat", typeof(string));
    
            var pacMatParameter = pacMat != null ?
                new ObjectParameter("pacMat", pacMat) :
                new ObjectParameter("pacMat", typeof(string));
    
            var nomPacParameter = nomPac != null ?
                new ObjectParameter("nomPac", nomPac) :
                new ObjectParameter("nomPac", typeof(string));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("sexo", sexo) :
                new ObjectParameter("sexo", typeof(string));
    
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var dirParameter = dir != null ?
                new ObjectParameter("dir", dir) :
                new ObjectParameter("dir", typeof(string));
    
            var disParameter = dis != null ?
                new ObjectParameter("dis", dis) :
                new ObjectParameter("dis", typeof(string));
    
            var telParameter = tel != null ?
                new ObjectParameter("tel", tel) :
                new ObjectParameter("tel", typeof(string));
    
            var celParameter = cel != null ?
                new ObjectParameter("cel", cel) :
                new ObjectParameter("cel", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var tipSagParameter = tipSag != null ?
                new ObjectParameter("TipSag", tipSag) :
                new ObjectParameter("TipSag", typeof(string));
    
            var talParameter = tal != null ?
                new ObjectParameter("Tal", tal) :
                new ObjectParameter("Tal", typeof(string));
    
            var pesoParameter = peso != null ?
                new ObjectParameter("Peso", peso) :
                new ObjectParameter("Peso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_insertarPaciente", pacPatParameter, pacMatParameter, nomPacParameter, sexoParameter, dniParameter, dirParameter, disParameter, telParameter, celParameter, emailParameter, tipSagParameter, talParameter, pesoParameter);
        }
    
        public virtual ObjectResult<usp_listarCita_Result> usp_listarCita()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listarCita_Result>("usp_listarCita");
        }
    
        public virtual ObjectResult<usp_listarCitaPaciente_Result> usp_listarCitaPaciente(string pcod)
        {
            var pcodParameter = pcod != null ?
                new ObjectParameter("pcod", pcod) :
                new ObjectParameter("pcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listarCitaPaciente_Result>("usp_listarCitaPaciente", pcodParameter);
        }
    
        public virtual ObjectResult<usp_listarDistrito_Result> usp_listarDistrito()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listarDistrito_Result>("usp_listarDistrito");
        }
    
        public virtual ObjectResult<usp_listarEmpleado_Result> usp_listarEmpleado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listarEmpleado_Result>("usp_listarEmpleado");
        }
    
        public virtual ObjectResult<usp_listarEmpleadoXtipo2_Result> usp_listarEmpleadoXtipo2(string tipo, string orden)
        {
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var ordenParameter = orden != null ?
                new ObjectParameter("orden", orden) :
                new ObjectParameter("orden", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listarEmpleadoXtipo2_Result>("usp_listarEmpleadoXtipo2", tipoParameter, ordenParameter);
        }
    
        public virtual ObjectResult<string> usp_listarEspecialidades()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_listarEspecialidades");
        }
    
        public virtual ObjectResult<usp_listarMedicamento_Result> usp_listarMedicamento()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listarMedicamento_Result>("usp_listarMedicamento");
        }
    
        public virtual ObjectResult<usp_listarMedicamentosPorTipo_Result> usp_listarMedicamentosPorTipo(string tipo)
        {
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listarMedicamentosPorTipo_Result>("usp_listarMedicamentosPorTipo", tipoParameter);
        }
    
        public virtual ObjectResult<usp_listarNombreCompleto_Result> usp_listarNombreCompleto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listarNombreCompleto_Result>("usp_listarNombreCompleto");
        }
    
        public virtual int usp_listarOrdenDeAtencion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_listarOrdenDeAtencion");
        }
    
        public virtual int usp_listarOrdenPaciente(string pcod)
        {
            var pcodParameter = pcod != null ?
                new ObjectParameter("pcod", pcod) :
                new ObjectParameter("pcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_listarOrdenPaciente", pcodParameter);
        }
    
        public virtual ObjectResult<usp_listarPaciente_Result> usp_listarPaciente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listarPaciente_Result>("usp_listarPaciente");
        }
    
        public virtual ObjectResult<usp_listarPacienteDistrito_Result> usp_listarPacienteDistrito(string cod_dis)
        {
            var cod_disParameter = cod_dis != null ?
                new ObjectParameter("cod_dis", cod_dis) :
                new ObjectParameter("cod_dis", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listarPacienteDistrito_Result>("usp_listarPacienteDistrito", cod_disParameter);
        }
    
        public virtual ObjectResult<usp_listarPacienteNombreCompleto_Result> usp_listarPacienteNombreCompleto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listarPacienteNombreCompleto_Result>("usp_listarPacienteNombreCompleto");
        }
    
        public virtual ObjectResult<string> usp_listarTipoMedicamento()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_listarTipoMedicamento");
        }
    
        public virtual ObjectResult<usp_login_Result> usp_login(string user, string password)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_login_Result>("usp_login", userParameter, passwordParameter);
        }
    
        public virtual ObjectResult<usp_obtener_usuario_Result> usp_obtener_usuario(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_obtener_usuario_Result>("usp_obtener_usuario", userParameter);
        }
    
        public virtual ObjectResult<usp_listarEmpleado_Result> ListarEmpleado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listarEmpleado_Result>("ListarEmpleado");
        }
    
        public virtual ObjectResult<usp_listarPaciente_Result> ListarPaciente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listarPaciente_Result>("ListarPaciente");
        }
    
        public virtual ObjectResult<usp_consultarPaciente_Result> ConsultarPaciente(string pcod)
        {
            var pcodParameter = pcod != null ?
                new ObjectParameter("pcod", pcod) :
                new ObjectParameter("pcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_consultarPaciente_Result>("ConsultarPaciente", pcodParameter);
        }
    
        public virtual ObjectResult<ListarDistrito_Result> ListarDistrito()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarDistrito_Result>("ListarDistrito");
        }
    
        public virtual ObjectResult<ListarEspecialidad_Result> ListarEspecialidad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarEspecialidad_Result>("ListarEspecialidad");
        }
    
        public virtual ObjectResult<ConsultarEmpleado_Result> ConsultarEmpleado(string ecod)
        {
            var ecodParameter = ecod != null ?
                new ObjectParameter("ecod", ecod) :
                new ObjectParameter("ecod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarEmpleado_Result>("ConsultarEmpleado", ecodParameter);
        }
    
        public virtual ObjectResult<usp_ListarUsuarios_Result> usp_ListarUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarUsuarios_Result>("usp_ListarUsuarios");
        }
    
        public virtual ObjectResult<usp_ListarUsuarios_Result> ListarUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarUsuarios_Result>("ListarUsuarios");
        }
    
        public virtual ObjectResult<usp_ConsultarEmpleadoEspecialidad_Result2> usp_ConsultarEmpleadoEspecialidad(string ecoesp)
        {
            var ecoespParameter = ecoesp != null ?
                new ObjectParameter("ecoesp", ecoesp) :
                new ObjectParameter("ecoesp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarEmpleadoEspecialidad_Result2>("usp_ConsultarEmpleadoEspecialidad", ecoespParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarEmpleadoEspecialidad_Result2> ConsultarEmpleadoEspecialidad(string ecoesp)
        {
            var ecoespParameter = ecoesp != null ?
                new ObjectParameter("ecoesp", ecoesp) :
                new ObjectParameter("ecoesp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarEmpleadoEspecialidad_Result2>("ConsultarEmpleadoEspecialidad", ecoespParameter);
        }
    
        public virtual ObjectResult<usp_ListarUsuMedicos_Result> usp_ListarUsuMedicos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarUsuMedicos_Result>("usp_ListarUsuMedicos");
        }
    
        public virtual ObjectResult<usp_ListarUsuMedicos_Result> ListarUsuMedicos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarUsuMedicos_Result>("ListarUsuMedicos");
        }
    
        public virtual ObjectResult<usp_ConsultarEmpEspecialidad_Result> usp_ConsultarEmpEspecialidad(string ecoesp)
        {
            var ecoespParameter = ecoesp != null ?
                new ObjectParameter("ecoesp", ecoesp) :
                new ObjectParameter("ecoesp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarEmpEspecialidad_Result>("usp_ConsultarEmpEspecialidad", ecoespParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarEmpEspecialidad_Result> ConsultarEmpEspecialidad(string ecoesp)
        {
            var ecoespParameter = ecoesp != null ?
                new ObjectParameter("ecoesp", ecoesp) :
                new ObjectParameter("ecoesp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarEmpEspecialidad_Result>("ConsultarEmpEspecialidad", ecoespParameter);
        }
    
        public virtual ObjectResult<usp_listarEmpleadoDistrito_Result1> usp_listarEmpleadoDistrito(string cod_dis)
        {
            var cod_disParameter = cod_dis != null ?
                new ObjectParameter("cod_dis", cod_dis) :
                new ObjectParameter("cod_dis", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listarEmpleadoDistrito_Result1>("usp_listarEmpleadoDistrito", cod_disParameter);
        }
    
        public virtual ObjectResult<usp_listarEmpleadoDistrito_Result1> ListarEmpleadoDistrito(string cod_dis)
        {
            var cod_disParameter = cod_dis != null ?
                new ObjectParameter("cod_dis", cod_dis) :
                new ObjectParameter("cod_dis", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listarEmpleadoDistrito_Result1>("ListarEmpleadoDistrito", cod_disParameter);
        }
    
        public virtual ObjectResult<ListarCitas_Result> ListarCitas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarCitas_Result>("ListarCitas");
        }
    
        public virtual ObjectResult<usp_listarCitaDoctor_Result> usp_listarCitaDoctor(string pcod)
        {
            var pcodParameter = pcod != null ?
                new ObjectParameter("pcod", pcod) :
                new ObjectParameter("pcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listarCitaDoctor_Result>("usp_listarCitaDoctor", pcodParameter);
        }
    
        public virtual ObjectResult<ConsultarEmpleadoCita_Result> ConsultarEmpleadoCita(string cod_dis)
        {
            var cod_disParameter = cod_dis != null ?
                new ObjectParameter("cod_dis", cod_dis) :
                new ObjectParameter("cod_dis", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarEmpleadoCita_Result>("ConsultarEmpleadoCita", cod_disParameter);
        }
    
        public virtual ObjectResult<ListarPacienteDistrito_Result1> ListarPacienteDistrito(string cod_dis)
        {
            var cod_disParameter = cod_dis != null ?
                new ObjectParameter("cod_dis", cod_dis) :
                new ObjectParameter("cod_dis", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarPacienteDistrito_Result1>("ListarPacienteDistrito", cod_disParameter);
        }
    
        public virtual ObjectResult<usp_listarPacienteTipoSangre_Result> usp_listarPacienteTipoSangre(string tipo_sangre)
        {
            var tipo_sangreParameter = tipo_sangre != null ?
                new ObjectParameter("tipo_sangre", tipo_sangre) :
                new ObjectParameter("tipo_sangre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listarPacienteTipoSangre_Result>("usp_listarPacienteTipoSangre", tipo_sangreParameter);
        }
    
        public virtual ObjectResult<ListarPacienteTipoSangre_Result1> ListarPacienteTipoSangre(string tipo_sangre)
        {
            var tipo_sangreParameter = tipo_sangre != null ?
                new ObjectParameter("tipo_sangre", tipo_sangre) :
                new ObjectParameter("tipo_sangre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarPacienteTipoSangre_Result1>("ListarPacienteTipoSangre", tipo_sangreParameter);
        }
    
        public virtual ObjectResult<usp_listarCitaEstadoFecha_Result> usp_listarCitaEstadoFecha(string estado, Nullable<System.DateTime> fechaini, Nullable<System.DateTime> fechafin)
        {
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var fechainiParameter = fechaini.HasValue ?
                new ObjectParameter("fechaini", fechaini) :
                new ObjectParameter("fechaini", typeof(System.DateTime));
    
            var fechafinParameter = fechafin.HasValue ?
                new ObjectParameter("fechafin", fechafin) :
                new ObjectParameter("fechafin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listarCitaEstadoFecha_Result>("usp_listarCitaEstadoFecha", estadoParameter, fechainiParameter, fechafinParameter);
        }
    
        public virtual ObjectResult<ConsultarCitaEstadoRango_Result1> ConsultarCitaEstadoRango(string estado, Nullable<System.DateTime> fechaini, Nullable<System.DateTime> fechafin)
        {
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var fechainiParameter = fechaini.HasValue ?
                new ObjectParameter("fechaini", fechaini) :
                new ObjectParameter("fechaini", typeof(System.DateTime));
    
            var fechafinParameter = fechafin.HasValue ?
                new ObjectParameter("fechafin", fechafin) :
                new ObjectParameter("fechafin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarCitaEstadoRango_Result1>("ConsultarCitaEstadoRango", estadoParameter, fechainiParameter, fechafinParameter);
        }
    }
}
