//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrySWII_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public Paciente()
        {
            this.Alergias = new HashSet<Alergias>();
            this.Citas = new HashSet<Citas>();
            this.Detalle_Receta = new HashSet<Detalle_Receta>();
            this.Examenes = new HashSet<Examenes>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public string IdPaciente { get; set; }
        public string ApePacPat { get; set; }
        public string ApePacMat { get; set; }
        public string NomPaciente { get; set; }
        public string Sexo { get; set; }
        public string NroIdentidad { get; set; }
        public string Direccion { get; set; }
        public string IdDistrito { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public string TipSangrePac { get; set; }
        public string TallaPac { get; set; }
        public string PesoPac { get; set; }
    
        public virtual ICollection<Alergias> Alergias { get; set; }
        public virtual ICollection<Citas> Citas { get; set; }
        public virtual ICollection<Detalle_Receta> Detalle_Receta { get; set; }
        public virtual Distrito Distrito { get; set; }
        public virtual ICollection<Examenes> Examenes { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
