//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrySWII_ADO
{
    using System;
    
    public partial class usp_obtener_usuario_Result1
    {
        public string IdUsuairo { get; set; }
        public string usuario { get; set; }
        public string contraseña { get; set; }
        public string estado { get; set; }
        public string IdPaciente { get; set; }
        public string Rol { get; set; }
    }
}
