//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrySWII_ADO
{
    using System;
    
    public partial class usp_ConsultarEmpleadoEspecialidad_Result2
    {
        public string ApeEmpMat { get; set; }
        public string ApeEmpPat { get; set; }
        public string NomEmpleado { get; set; }
        public string IdEmpleado { get; set; }
    }
}
